image: jangrewe/gitlab-ci-android

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  tags: 
  - shared
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - ./*/build/outputs/apk/debug/*.apk
    - ./*/build/outputs/aar/*.aar

